{{- define "gpu-tel.serviceAccount" -}}
{{- $root := . -}}
{{- range $name, $subchart := .Values.subcharts -}}
{{- if $subchart.enabled -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  labels:
    {{- include "gpu-tel.labels" $root | nindent 4 }}
{{- end -}}
{{- end -}}
{{- end -}}
