apiVersion: v2
name: gpu-tel
description: A Helm chart for GPU Telemetry
version: 0.1.0
appVersion: "1.0.0"
type: application

# Dependencies for subcharts
dependencies:
  - name: mq-service
    version: 0.1.0
    repository: file://./charts/mq-service
    condition: subcharts.mq-service.enabled
  - name: telemetry-streamer
    version: 0.1.0
    repository: file://./charts/telemetry-streamer
    condition: subcharts.telemetry-streamer.enabled
  - name: sink
    version: 0.1.0
    repository: file://./charts/sink
    condition: subcharts.sink.enabled
