apiVersion: v2
name: gpu-tel
description: A Helm chart for GPU Telemetry
version: 0.1.0
appVersion: "1.0.0"
type: application

# Dependencies for subcharts
dependencies:
  - name: api-server
    version: 0.1.0
    repository: file://./charts/api-server
    condition: subcharts.api-server.enabled
  - name: mq-service
    version: 0.1.0
    repository: file://./charts/mq-service
    condition: subcharts.mq-service.enabled
  - name: telemetry-collector
    version: 0.1.0
    repository: file://./charts/telemetry-collector
    condition: subcharts.telemetry-collector.enabled
  - name: telemetry-streamer
    version: 0.1.0
    repository: file://./charts/telemetry-streamer
    condition: subcharts.telemetry-streamer.enabled
  - name: sink
    version: 0.1.0
    repository: file://./charts/sink
    condition: subcharts.sink.enabled
