apiVersion: v1
kind: Service
metadata:
  name: {{ include "mq-service.fullname" . }}
  labels:
    {{- include "mq-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: mq
      protocol: TCP
      name: mq
  selector:
    {{- include "mq-service.selectorLabels" . | nindent 4 }}
