apiVersion: v1
kind: Service
metadata:
  name: {{ include "gpu-tel.fullname" . }}-api-service
  labels:
    {{- include "gpu-tel.labels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "gpu-tel.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api-server
