apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gpu-tel.fullname" . }}-telemetry-collector
  labels:
    {{- include "gpu-tel.labels" . | nindent 4 }}
    app.kubernetes.io/component: telemetry-collector
spec:
  replicas: {{ .Values.services.telemetryCollector.replicaCount }}
  selector:
    matchLabels:
      {{- include "gpu-tel.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: telemetry-collector
  template:
    metadata:
      labels:
        {{- include "gpu-tel.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: telemetry-collector
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gpu-tel.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-telemetry-collector
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.images.telemetryCollector.repository }}:{{ .Values.images.telemetryCollector.tag }}"
          imagePullPolicy: {{ .Values.images.telemetryCollector.pullPolicy }}
          command: ["/app/telemetry-collector"]
          resources:
            {{- toYaml .Values.services.telemetryCollector.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "gpu-tel.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
